### ISSUE TITLE
"Spawning Item into inventory"

### ISSUE THREAD

**Issue by lordvergo** [henry232323/RPGBot#15]
Hello,
I am not able to read code very well. However, as a moderator I was not able to "spawn" items into a person's inventory based on the sequences given. 

"rp!inventory giveitem"

Seems to search for a member "give item" other sequences used did not seem to work.

I was curious if it was left out or I am using the incorrect sequence, as I cannot read code and nearly blew my head looking at it through my simple understanding of logic.

Regards.

**Comment by henry232323** [comment]
The website is a little outdated. The command is `rp!giveitem`
Take a look at `rp!help giveitem`
Also if you have further questions, please ask in the official support server, there is a link in the `rp!help` description.
