### ISSUE TITLE
[Rus] Sorry, i no english

### ISSUE THREAD

**Issue by FoxyLazarov** [henry232323/RPGBot#18]
Здравствуйте,

Хотелось спросить, в GitHub полный код бота? Просто хотелось мне перевести его на русский и доделать/переделать несколько команд. Вы же не против? (Я не забуду вас упомянут вас на моём сервере)

**Comment by henry232323** [comment]
К сожалению, я не русский! Однако у меня есть перевод Google. Полный бот-код здесь да. Если вы хотите добавить дополнительную поддержку или изменить что-либо, вы можете отправить запрос на вытягивание. По большей части бот уже переведен, но я еще не сделал этого, поэтому языки можно переключить.

**Comment by FoxyLazarov** [comment]
А какой commands?

**Comment by henry232323** [comment]
Если вы хотите добавить или изменить команды, вы можете отправить запрос на вытягивание.

**Comment by FoxyLazarov** [comment]
Окей

И ещё у вас есть баганые (bugs) команды, к примеру rp!team addmember

**Comment by henry232323** [comment]
Если у меня есть ошибки, вы можете исправить их

**Comment by FoxyLazarov** [comment]
Хорошо, попытаюсь исправить. Просто я немного пинот не понимаю

**Comment by FoxyLazarov** [comment]
Closed

**Comment by henry232323** [comment]
пинот ?

**Comment by FoxyLazarov** [comment]
Сорри, перепутал. python3

**Comment by FoxyLazarov** [comment]
Can you help with the python?

**Comment by henry232323** [comment]
What with?

**Comment by henry232323** [comment]
Thats not something I can do, no.

**Comment by Mozyl** [comment]
I also can help with translate.

**Comment by FoxyLazarov** [comment]
Не надо, я сам перевожу

**Comment by Mozyl** [comment]
Я видел, ты хотя бы проверяй написание

**Comment by FoxyLazarov** [comment]
Как ты видел, если я ещё не заливал сюда

**Comment by Mozyl** [comment]
Я видел чей-то перевод на русском. В translate.json. может это Генри через Гугл  или ещё кто-то. Там была ошибка в переводе, написании и не дописано слово. Я ему уже отправил часть перевода.

**Comment by henry232323** [comment]
Я только переводил французский, а не русский. Также не забудьте использовать newtranslations.json

**Comment by Mozyl** [comment]
Ок
