### ISSUE TITLE
Translation support!

### ISSUE THREAD

**Issue by henry232323** [henry232323/RPGBot#3]
I need help setting up translations! Anyone willing to help is welcome to PR

**Comment by SahilAgarwal321** [comment]
Can you give more info on this??

**Comment by henry232323** [comment]
Ok so, so far I've set up a file, translations.json which will contain all translation data. So far it's incomplete with only the French translation. It's set up that each command has several messages it could return, and those are indexed as they appear in the code. 
The file is set up like this in a json format
```json
"language code": {
    "Cog Name": {
         "commandname": [
             "Command message"
         ]
    }
}   
```
Ish, take a look at the model but be wary it's incomplete

**Comment by rafajaques** [comment]
I would like to help.
Just translate and send a new file? How to name it?

**Comment by arthrez** [comment]
Hello, I don't know anything about programing, but i can help translating from english to brazillian portuguese :)

**Comment by henry232323** [comment]
Before we can start making translations unfortunately, we need to actually implement the translation part and and finish the template

**Comment by marielfrank** [comment]
Would it make sense to use the Google Translation API for this?
https://cloud.google.com/translate/docs/

**Comment by henry232323** [comment]
Translations aren't very good from Google translate, when we can have direct translations. In any case Google makes its APIs paid and that isn't worth my money, nor is trying to scrape it.

**Comment by Sakiut** [comment]
If you need help for the French Translations, call me!

**Comment by krns** [comment]
Had a look into the german translations and did some improvements :)

**Comment by geekfred** [comment]
Want me to add Spanish and English to the json file? :D

**Comment by henry232323** [comment]
If you take a look at the current file, would you be willing to do English (Spanish would be a lot to ask but we need that too) for _all_ commands, not just the ones we have currently? You can rip the text straight from the source code

**Comment by geekfred** [comment]
Yeah sure, I can.

**Comment by Philip-Nicolas** [comment]
Current French is a disaster, will update translations to fix grammar.

**Comment by hndr91** [comment]
Can I do for Indonesian ?

**Comment by henry232323** [comment]
Feel free!

**Comment by hndr91** [comment]
Sir, where is the default translation? I need the english version. Thx @henry232323

**Comment by henry232323** [comment]
Oh sorry! Unfortunately as of now the English doesn't actually exist. It all needs to be mapped from the source code, you can do that if you're interested though.

**Comment by hndr91** [comment]
@henry232323 okay, got it sir,

**Comment by henry232323** [comment]
Since all the responses are hard coded, they can be copy pasted from the source.

**Comment by Mozyl** [comment]
Hello, I can help with transportation on rus. I saw rus. Transportation, but with some mistakes.

**Comment by Mozyl** [comment]
Translate*

**Comment by henry232323** [comment]
If you would be willing to start working with the new translation format, we have a file, newtranslations.json that can be edited.

**Comment by FoxyLazarov** [comment]
А также этим занимаюсь я с переводом на английский, а также добавление новых функций

**Comment by donkeymonkey1** [comment]
I can make serbia translation if you need

**Comment by henry232323** [comment]
Feel free
