### ISSUE TITLE
HTTP error??

### ISSUE THREAD

**Issue by FourWindBadger** [henry232323/RPGBot#33]
Hello. i have  an issue.
I tried to create an item with the rp!settings additem, and then i filled out the information etc, and then it creates it and then i went to check on it by doing rp!settings iteminfo Ion-Rifle
 and i get this error  

Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In embed.thumbnail.url: Not a well formed URL

i happend after i tried to update an existing item(by remaking the same item with the same name without deleting the old one) It then started to bug out and no matter what i new item i make it fucks up like that (worked before i tried to correct my file) 
and my 2nd question if you make a mistake how do i delete information from it ? (like i want the image file, then Damage: +1 and i completely spell the damaged part wrong? (and need to delete it)

**Comment by Potzerus** [comment]
Heya 
This error usually means that something that wasnt a link was put in after image:
for further questions or help i suggest joining the bot support discord server

https://discord.gg/bFX73pf

**Comment by FourWindBadger** [comment]
but shouldnt i be able to use the Additional information? for image etc? Like image: http what ever Strenght 200, Dex 200 (as example) ? (also tried to seperate it with commas but that gave me an error

**Comment by FourWindBadger** [comment]
fixed
