### ISSUE TITLE
Character's Balance Error

### ISSUE THREAD

**Issue by Crazyboycory22** [henry232323/RPGBot#36]
Whenever I use the rp!chareco command for a character, it doesn't work. For example, if I type in rp!chareco Test it'll give me this error message:

Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In embed.author.icon_url: Not a well formed URL. If this is unexpected, please report this to the bot creator

I don't know if I'm doing something wrong or if I'm missing something. If I am, please tell me, but I do believe that the command isn't working properly. I tried the command both when I had the character assumed and unassumed and it didn't make a difference.

**Comment by henry232323** [comment]
This has been fixed
