### ISSUE TITLE
Hi I try to load the example file of the items 

### ISSUE THREAD

**Issue by wildrakbil** [henry232323/RPGBot#60]
me: rp!loaditems replace Items_Example.xlsx
RPGBot: 'utf-8' codec can't decode byte 0x8a in position 11: invalid start byte If this is unexpected, please report this to the bot creator

**Comment by henry232323** [comment]
Loading items requires a csv file, and doesn't appear to be compatible with CSVs exported from Excel, try importing into google sheets then exporting as a csv
