### ISSUE TITLE
I Can't Assign Salaries for roles. 

### ISSUE THREAD

**Issue by MarleyC1** [henry232323/RPGBot#62]
When i pull up my character it says i have the @Moderator role i gave myself, however when i tag moderator in the role section of 
rp!salary create <role> <interval> [items_or_number...] with the proper interval and number, the bot says "Role could not be found"

**Comment by henry232323** [comment]
Can you show the exact command you run

**Comment by MarleyC1** [comment]
I Use: 

rp!salary create @moderators 86400 1000

It even lets me tag the role

It’s honestly probably something I’m doing wrong, I started using bots very recently so I’m still a bit finicky with them 



Sent from App for Gmail


Tuesday, May 4, 2021, 3:25 PM -0400 from ***@***.***  ***@***.***>:

**Comment by henry232323** [comment]
I see, please join our support server and we'll see what we can do.
https://discord.gg/mXZg2mk 

I also recommend looking RPGBot-V2, its everything that RPGBot is but better.
