### ISSUE TITLE
you cannot import Shops or Shopitems

### ISSUE THREAD

**Issue by Kioshkio** [henry232323/RPGBot#66]
idk why its happening but you can not import Shops and Shopitems

![┃𝗢𝗪𝗡𝗘𝗥-𝗢𝗡𝗟𝗬 - Discord 11 10 2021 16_02_54 (2)](https://user-images.githubusercontent.com/92373550/136950158-6e93e52a-cede-471e-973e-9a40a9ac15d4.png)

**Comment by Potzerus** [comment]
remove the quotes around the numbers in the first file but keep it as it is otherwise
