### ISSUE TITLE
_auth

### ISSUE THREAD

**Issue by Gentle-Ego** [henry232323/RPGBot#71]
There is no file auth.json in resources or in the project, so the bot will never start

**Comment by henry232323** [comment]
The bot doesn't really support self hosting. The Github version is missing a few parts of the environment / integration at the moment that would be necessary as well, such as the database. Our only currently supported bot is [RPGBot-V2](https://top.gg/bot/673737213959208980) which is not open source.

**Comment by Gentle-Ego** [comment]
oh ok, thx for telling me this!
